### ISSUE TITLE
nanopub-java support for windows?

### ISSUE THREAD

**Issue by svenvanderburg** [Nanopublication/nanopub-java#8]
I am trying to use `nanopub-java` on windows, I wrote [this batch script](https://github.com/fair-workflows/nanopub/blob/ad93ffe09ba19b717640cf69765dfadf61b0bd30/bin/nanopub-java.bat) that seems to work, but if I run:
```nanopub-java mkkeys -a RSA -f 'C:/Users/sven/.nanopub/id'```
I get:
```
Error: Could not find or load main class mkkeys
```
I get this when locally testing on Windows 10.

[In this github action](https://github.com/fair-workflows/nanopub/pull/107/checks?check_run_id=1594421404) I get a slightly different but seemingly related error. 

I don't think `nanopub-java` is supported on windows, but can it be? For the users of the [python nanopub client](https://github.com/fair-workflows/nanopub) (whom we expect to mostly be on windows) this would be really useful!

**Comment by tkuhn** [comment]
I haven't tested it on Windows really, but it should work. Does this error only show up with the `mkkeys` command or with other commands too?

**Comment by svenvanderburg** [comment]
For `nanopub-java publish`:
```Error: Could not find or load main class publish```
For `nanopub-java sign`:
```Error: Could not find or load main class sign```

Seems like there is a pattern... 😉

**Comment by svenvanderburg** [comment]
[Some simple googling](https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean) makes me think this is in my batch script and not in the `nanopub-java` code.

**Comment by svenvanderburg** [comment]
I fixed the [batch script](https://github.com/fair-workflows/nanopub/blob/3ba6f0184e518d1f99ed9b55316e237f56828dfd/bin/nanopub-java.bat). Now the `mkkeys` command works. But the `sign` command produces:

```
C:\Users\sven\anaconda3\bin\..\lib\nanopub-1.32-jar-with-dependencies.
at java.io.FileNotFoundException: C:Userssven\.nanopub\id_rsa (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method) 
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source) 
at java.io.FileInputStream.<init>(Unknown Source)
at org.nanopub.extra.security.SignNanopub.loadKey(SignNanopub.java:212)
 at org.nanopub.extra.security.SignNanopub.run(SignNanopub.java:103)
at org.nanopub.extra.security.SignNanopub.main(SignNanopub.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source) 
 at org.nanopub.Run.run(Run.java:76)
 at org.nanopub.Run.main(Run.java:27) 
```

**Comment by tkuhn** [comment]
Yes, seems to be a problem when backslashes in Windows paths are involved. I fixed it (I hope) in the latest commit: https://github.com/Nanopublication/nanopub-java/blob/master/src/main/java/org/nanopub/extra/security/SignNanopub.java#L210

**Comment by svenvanderburg** [comment]
Thanks @tkuhn! When do you expect to release this? Or how could I test it before release?

**Comment by tkuhn** [comment]
Can you test it with this? [nanopub-1.33-SNAPSHOT-jar-with-dependencies.jar.zip](https://github.com/Nanopublication/nanopub-java/files/5764036/nanopub-1.33-SNAPSHOT-jar-with-dependencies.jar.zip)

**Comment by svenvanderburg** [comment]
I now get an error on linux when using the `-f` option:
`nanopub-java mkkeys -a RSA -f /Users/user/.nanopub/id_rsa`
```
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1026)
	at org.nanopub.extra.security.MakeKeys.make(MakeKeys.java:66)
	at org.nanopub.extra.security.MakeKeys.run(MakeKeys.java:49)
	at org.nanopub.extra.security.MakeKeys.main(MakeKeys.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.nanopub.Run.run(Run.java:76)
	at org.nanopub.Run.main(Run.java:27)
```
This does not happen with version 1.32

**Comment by tkuhn** [comment]
Right, I know what I did wrong. I will correct it...

**Comment by tkuhn** [comment]
Can you try this? 
[Uploading nanopub-1.33-SNAPSHOT-jar-with-dependencies.jar.zip…]()

**Comment by svenvanderburg** [comment]
Works like a charm 👍 Thanks a lot 🙏  See [first publication using nanopub from windows](http://test-server.nanopubs.lod.labs.vu.nl/RAF3HxztXc4khstGdPukcONQX1XhUSoe8FK8yR-S6GX-4)

**Comment by tkuhn** [comment]
Great to hear. I made a new release too: https://github.com/Nanopublication/nanopub-java/releases/tag/nanopub-1.33

**Comment by svenvanderburg** [comment]
Fixed and released, so closing issue!
